# Site settings
title: Jeremy Axelrod
email: axelrod.jeremy@gmail.com
description: "A Ruby and Javascript developer who specializes in Ruby on Rails and AngularJS"
baseurl: ""
url: "http://jeaxel.com"

# Build settings
markdown: kramdown
permalink: pretty
